# Generated by Django 2.0.1 on 2018-01-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20180119_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='adduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('dateofjoin', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotelservice',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
