# Generated by Django 2.0.1 on 2018-01-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20180119_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='email',
        ),
    ]
