# Generated by Django 2.0.1 on 2018-01-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_adduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='adduser',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
